import { expect, test } from '@playwright/test'

test('shell navigation and core interactions', async ({ page }) => {
  await page.goto('/incidents')
  await expect(page.getByTestId('app-sidebar')).toBeAttached()
  await expect(page.getByTestId('incidents-page')).toBeVisible()
  await page.getByRole('button', { name: '搜索' }).last().click()
  await expect(page.getByRole('dialog', { name: '全局搜索' })).toBeVisible()
  await page.getByPlaceholder('搜索事件、服务、成员或变更…').fill('checkout')
  await expect(page.getByText(/Checkout/).first()).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '创建事件' }).last().click()
  await expect(page.getByRole('dialog', { name: '创建事件' })).toBeVisible()
  await page.getByLabel('标题 *').fill('E2E smoke incident')
  await page.getByRole('button', { name: '提交事件' }).click()
  await expect(page.getByText(/已创建 OPS-/)).toBeVisible()
  await page.goto('/board')
  await expect(page.getByTestId('board-page')).toBeVisible()
  await page.goto('/settings')
  await expect(page.getByTestId('settings-page')).toBeVisible()
})
