import { useState } from 'react'
import { Bell, Check, Globe2, KeyRound, Plus, Save, Shield, Trash2, UserPlus, Users, Webhook } from 'lucide-react'
import { PageHeader } from '../components/shell'
import { Avatar, Badge, Button, Card, Dialog, Input, Select, Tabs, Textarea } from '../components/ui'
import { integrations as seedIntegrations, notificationRules as seedRules, team } from '../data/mock'
import { useWorkbench } from '../store'

const tabs = [
  { id: 'general', label: '基本信息' },
  { id: 'members', label: '成员与权限' },
  { id: 'teams', label: '团队' },
  { id: 'notifications', label: '通知规则' },
  { id: 'integrations', label: '集成' },
  { id: 'preferences', label: '个人偏好' },
]

export function SettingsPage() {
  const { settings, updateSettings, pushToast } = useWorkbench()
  const [tab, setTab] = useState('general')
  const [saving, setSaving] = useState(false)
  const [dirty, setDirty] = useState(false)
  const [inviteOpen, setInviteOpen] = useState(false)
  const [invite, setInvite] = useState({ email: '', role: 'member', team: 'Platform' })
  const [inviteError, setInviteError] = useState('')
  const [integrations, setIntegrations] = useState(seedIntegrations)
  const [rules, setRules] = useState(seedRules)
  const save = () => { setSaving(true); window.setTimeout(() => { setSaving(false); setDirty(false); pushToast({ tone: 'success', title: '设置已保存' }) }, 500) }
  const testIntegration = (id: string) => { setSaving(true); window.setTimeout(() => { setSaving(false); pushToast({ tone: id === 'int-email' ? 'error' : 'success', title: id === 'int-email' ? '连接测试失败' : '连接测试成功', message: '本地演示没有发出真实请求。' }) }, 500) }
  return <div className="flex h-full flex-col" data-testid="settings-page">
    <PageHeader title="工作区设置" description="成员、通知、集成与个人偏好。" actions={<><Button variant="ghost" disabled={!dirty} onClick={() => { setDirty(false); pushToast({ tone: 'info', title: '已放弃未保存修改' }) }}>取消</Button><Button variant="primary" disabled={saving} onClick={save}>{saving ? '保存中…' : <><Save className="size-4" />保存</>}</Button></>} toolbar={<Tabs items={tabs} value={tab} onChange={setTab} />} />
    <div className="min-h-0 flex-1 overflow-auto p-3">
      {tab === 'general' && <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_320px]"><Card className="p-5"><h2 className="text-[14px] font-semibold">工作区信息</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-[12px]"><span>名称</span><Input value={settings.workspaceName} onChange={(event) => { updateSettings({ workspaceName: event.target.value }); setDirty(true) }} /></label><label className="grid gap-1.5 text-[12px]"><span>默认时区</span><Select value={settings.timezone} onChange={(event) => { updateSettings({ timezone: event.target.value }); setDirty(true) }}><option>Asia/Shanghai</option><option>UTC</option><option>America/Los_Angeles</option></Select></label><div className="sm:col-span-2"><label className="grid gap-1.5 text-[12px]"><span>描述</span><Textarea value={settings.description} onChange={(event) => { updateSettings({ description: event.target.value }); setDirty(true) }} /></label></div><label className="grid gap-1.5 text-[12px]"><span>默认事件状态</span><Select value={settings.defaultIncidentStatus} onChange={(event) => { updateSettings({ defaultIncidentStatus: event.target.value as typeof settings.defaultIncidentStatus }); setDirty(true) }}><option value="open">Open</option><option value="investigating">Investigating</option></Select></label></div></Card><Card className="p-5"><h2 className="text-[14px] font-semibold">危险区域</h2><p className="mt-2 text-[12px] text-[var(--text-muted)]">删除工作区会移除全部事件、服务和成员关联。</p><Button variant="danger" className="mt-5 w-full" onClick={() => useWorkbench.getState().requestConfirm({ title: '删除工作区？', message: '这是一个高危操作，演示中不会真正删除。', confirmLabel: '删除工作区', onConfirm: () => pushToast({ tone: 'error', title: '演示模式已阻止删除' }) })}><Trash2 className="size-4" />删除工作区</Button></Card></div>}
      {tab === 'members' && <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--border)] p-4"><div><h2 className="text-[14px] font-semibold">成员与权限</h2><p className="mt-1 text-[11px] text-[var(--text-faint)]">{team.length} 位成员</p></div><Button variant="primary" onClick={() => setInviteOpen(true)}><UserPlus className="size-4" />邀请成员</Button></div><table className="w-full min-w-[680px] text-left text-[12px]"><thead className="bg-[var(--surface-hover)] text-[11px] text-[var(--text-faint)]"><tr><th className="px-4 py-2 font-medium">成员</th><th className="px-4 py-2 font-medium">角色</th><th className="px-4 py-2 font-medium">团队</th><th className="px-4 py-2 font-medium">状态</th><th className="px-4 py-2 font-medium">操作</th></tr></thead><tbody>{team.map((member) => <tr key={member.id} className="border-t border-[var(--border)]"><td className="px-4 py-3"><div className="flex items-center gap-2"><Avatar name={member.name} /><div><div className="font-medium">{member.name}</div><div className="text-[10px] text-[var(--text-faint)]">{member.email}</div></div></div></td><td className="px-4 py-3"><Select value={member.role.toLowerCase().includes('lead') ? 'admin' : 'member'} onChange={() => pushToast({ tone: 'success', title: '角色已更新' })}><option value="admin">Admin</option><option value="member">Member</option><option value="viewer">Viewer</option></Select></td><td className="px-4 py-3 text-[var(--text-muted)]">{member.team}</td><td className="px-4 py-3"><Badge tone={member.status === 'active' ? 'success' : 'warning'}>{member.status}</Badge></td><td className="px-4 py-3"><Button size="sm" variant="ghost" onClick={() => pushToast({ tone: 'info', title: `${member.name} 已暂停` })}>暂停</Button></td></tr>)}</tbody></table></Card>}
      {tab === 'teams' && <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{['Platform', 'Core', 'Web', 'Data', 'Support', 'Release'].map((name, index) => <Card key={name} className="p-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-lg bg-[var(--brand-soft)] text-[var(--brand)]"><Users className="size-4" /></div><div><div className="text-[13px] font-semibold">{name}</div><div className="text-[11px] text-[var(--text-faint)]">{2 + index} 位成员 · {index + 1} 个服务</div></div><Button size="sm" variant="ghost" className="ml-auto">编辑</Button></div></Card>)}</div>}
      {tab === 'notifications' && <Card className="p-4"><div className="flex items-center justify-between"><div><h2 className="text-[14px] font-semibold">通知规则</h2><p className="mt-1 text-[11px] text-[var(--text-faint)]">控制事件、变更和摘要的通知渠道。</p></div><Button variant="primary" onClick={() => setRules((current) => [...current, { id: `rule-${current.length + 1}`, name: '新规则', event: 'incident.updated', severity: 'medium', channel: 'Slack', quiet: 'never', enabled: true }])}><Plus className="size-4" />新建规则</Button></div><div className="mt-4 space-y-2">{rules.map((rule) => <div key={rule.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-[var(--border)] p-3 text-[12px]"><Bell className="size-4 text-[var(--text-faint)]" /><span className="font-medium">{rule.name}</span><Badge>{rule.event}</Badge><span className="text-[var(--text-muted)]">{rule.channel}</span><span className="text-[var(--text-faint)]">静默 {rule.quiet}</span><label className="ml-auto flex items-center gap-2"><input type="checkbox" checked={rule.enabled} onChange={() => setRules((current) => current.map((item) => item.id === rule.id ? { ...item, enabled: !item.enabled } : item))} />启用</label><Button size="sm" variant="ghost" onClick={() => pushToast({ tone: 'success', title: '规则已保存' })}>编辑</Button></div>)}</div></Card>}
      {tab === 'integrations' && <div className="grid gap-3 lg:grid-cols-2">{integrations.map((integration) => <Card key={integration.id} className="p-4"><div className="flex items-start gap-3"><div className="grid size-9 place-items-center rounded-lg bg-[var(--surface-hover)]">{integration.kind === 'webhook' ? <Webhook className="size-4" /> : integration.kind === 'slack' ? <Bell className="size-4" /> : <Globe2 className="size-4" />}</div><div><div className="text-[13px] font-semibold">{integration.name}</div><div className="mt-1 text-[11px] text-[var(--text-faint)]">{integration.target}</div></div><Badge className="ml-auto" tone={integration.enabled ? 'success' : 'neutral'}>{integration.enabled ? 'enabled' : 'disabled'}</Badge></div><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => testIntegration(integration.id)}>测试连接</Button><Button size="sm" variant="ghost" onClick={() => setIntegrations((current) => current.map((item) => item.id === integration.id ? { ...item, enabled: !item.enabled } : item))}>{integration.enabled ? '停用' : '启用'}</Button><Button size="sm" variant="ghost" className="ml-auto" onClick={() => setIntegrations((current) => current.filter((item) => item.id !== integration.id))}><Trash2 className="size-4" />删除</Button></div></Card>)}<Card className="grid min-h-32 place-items-center border-dashed p-4 text-center"><div><Webhook className="mx-auto size-5 text-[var(--text-faint)]" /><p className="mt-2 text-[12px] text-[var(--text-muted)]">添加新的 Webhook 集成</p><Button className="mt-3" size="sm" onClick={() => setIntegrations((current) => [...current, { id: `int-${current.length + 1}`, name: 'New webhook', kind: 'webhook', enabled: false, target: 'https://example.test/hook' }])}>新增 Webhook</Button></div></Card></div>}
      {tab === 'preferences' && <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_320px]"><Card className="p-5"><h2 className="text-[14px] font-semibold">个人偏好</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-[12px]"><span>默认首页</span><Select value={settings.defaultHome} onChange={(event) => { updateSettings({ defaultHome: event.target.value }); setDirty(true) }}><option value="/inbox">收件箱</option><option value="/incidents">事件列表</option><option value="/board">看板</option></Select></label><label className="grid gap-1.5 text-[12px]"><span>时区</span><Select value={settings.timezone} onChange={(event) => { updateSettings({ timezone: event.target.value }); setDirty(true) }}><option>Asia/Shanghai</option><option>UTC</option></Select></label></div><div className="mt-5 space-y-3"><ToggleRow label="通知" description="接收分派、提及和状态变化通知" checked={settings.notifications} onChange={(value) => { updateSettings({ notifications: value }); setDirty(true) }} /><ToggleRow label="快捷键" description="启用全局搜索和创建事件快捷键" checked={settings.shortcuts} onChange={(value) => { updateSettings({ shortcuts: value }); setDirty(true) }} /></div></Card><Card className="p-5"><h2 className="text-[14px] font-semibold">安全</h2><div className="mt-4 space-y-3"><div className="flex items-center gap-3"><KeyRound className="size-4 text-[var(--text-faint)]" /><div><div className="text-[12px] font-medium">API 令牌</div><div className="text-[11px] text-[var(--text-faint)]">2 个活跃令牌</div></div><Button size="sm" variant="ghost" className="ml-auto">管理</Button></div><div className="flex items-center gap-3"><Shield className="size-4 text-[var(--text-faint)]" /><div><div className="text-[12px] font-medium">双因素认证</div><div className="text-[11px] text-[var(--text-faint)]">已启用</div></div><Badge className="ml-auto" tone="success">enabled</Badge></div></div></Card></div>}
    </div>
    <Dialog open={inviteOpen} onClose={() => setInviteOpen(false)} title="邀请成员" footer={<><Button variant="ghost" onClick={() => setInviteOpen(false)}>取消</Button><Button variant="primary" onClick={() => { if (!invite.email.includes('@')) { setInviteError('请输入有效邮箱'); return } setInviteOpen(false); setInviteError(''); pushToast({ tone: 'success', title: '邀请已发送', message: invite.email }) }}>发送邀请</Button></>}><div className="grid gap-4"><label className="grid gap-1.5 text-[12px]"><span>邮箱</span><Input type="email" value={invite.email} onChange={(event) => setInvite({ ...invite, email: event.target.value })} placeholder="name@example.test" /></label><label className="grid gap-1.5 text-[12px]"><span>角色</span><Select value={invite.role} onChange={(event) => setInvite({ ...invite, role: event.target.value })}><option value="member">Member</option><option value="admin">Admin</option><option value="viewer">Viewer</option></Select></label><label className="grid gap-1.5 text-[12px]"><span>团队</span><Select value={invite.team} onChange={(event) => setInvite({ ...invite, team: event.target.value })}>{['Platform', 'Core', 'Web', 'Data', 'Support', 'Release'].map((item) => <option key={item}>{item}</option>)}</Select></label>{inviteError && <div className="text-[12px] text-[var(--danger)]">{inviteError}</div>}</div></Dialog>
  </div>
}

function ToggleRow({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center gap-3 rounded-lg border border-[var(--border)] p-3"><div><div className="text-[12px] font-medium">{label}</div><div className="text-[11px] text-[var(--text-faint)]">{description}</div></div><label className="ml-auto"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label></div> }
